#!/usr/bin/env bash
set -euo pipefail

# This file is bind-mounted read-only into the scoreboard container. Keep the
# format intentionally simple so the Node server can parse it without tools:
# <interface name><tab><IP address>
output_file="${NETWORK_INFO_FILE:-/var/lib/bewerbsboard/network_info.txt}"
output_directory="$(dirname "$output_file")"

mkdir -p "$output_directory"

write_network_info() {
  local new_content
  new_content="$(
    printf '# Generated by bewerbsboard-network-info.service; do not edit.\n'
    ip -o addr show scope global | awk '
      $3 == "inet" {
        interface_name = $2
        sub(/@.*/, "", interface_name)
        split($4, address, "/")
        print interface_name "\t" address[1]
      }
    '
  )"

  if [ -f "$output_file" ]; then
    local current_content
    current_content="$(cat "$output_file" 2>/dev/null || true)"
    if [ "$new_content" = "$current_content" ]; then
      return 0
    fi
  fi

  local temporary_file
  temporary_file="$(mktemp "$output_directory/.network_info.XXXXXX")"
  printf '%s\n' "$new_content" > "$temporary_file"

  chmod 0644 "$temporary_file"
  mv -f "$temporary_file" "$output_file"
}

while true; do
  write_network_info
  sleep 10
done
