#!/usr/bin/env bash
#
# A wizard — walks a human through configuring and deploying BewerbsBoard.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  This wizard guides you through demo mode, local Docker deployment,\n' "$DIM"
  printf '  Cloudflare Pages provisioning, or Keycloak/oauth2-proxy configuration.\n'
  printf '  Stop any time with Ctrl-C and re-run later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current (%s)]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$current" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Operation complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} )) && note "configured ${#WRITTEN_ENV[@]} setting(s) in $ENV_FILE: ${WRITTEN_ENV[*]}"
  printf '\n'
}

# Helper: check port availability
_check_port_available() {
  local port="$1"
  if command -v ss >/dev/null 2>&1; then
    ! ss -ltn "( sport = :$port )" | grep -q ":$port"
  elif command -v lsof >/dev/null 2>&1; then
    ! lsof -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1
  else
    true
  fi
}

# Helper: generate random base64 string
_generate_random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32
  elif command -v node >/dev/null 2>&1; then
    node -e "console.log(require('crypto').randomBytes(32).toString('base64'))"
  elif command -v python3 >/dev/null 2>&1; then
    python3 -c "import secrets, base64; print(base64.b64encode(secrets.token_bytes(32)).decode())"
  else
    date +%s | sha256sum | base64 | head -c 32
  fi
}

# Helper: generate the unified app.sh control script
_generate_control_scripts() {
  local compose_file="$1"
  step "Generating control script (app.sh)..."

  cat <<EOF > app.sh
#!/usr/bin/env bash
set -euo pipefail
cd "\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
PROJECT_NAME="$PROJECT_NAME"
COMPOSE_FILE="$compose_file"

usage() {
  printf 'Usage: ./app.sh <start|stop|delete> [--yes]\n'
}

case "\${1:-}" in
  start)
    echo "Starting BewerbsBoard stack (\$PROJECT_NAME)..."
    docker compose --project-name "\$PROJECT_NAME" -f "\$COMPOSE_FILE" up -d --build --wait
    ;;
  stop)
    echo "Stopping BewerbsBoard stack (\$PROJECT_NAME)..."
    docker compose --project-name "\$PROJECT_NAME" -f "\$COMPOSE_FILE" stop
    ;;
  delete)
    echo "This will stop and remove containers, networks, and data volumes for BewerbsBoard (\$PROJECT_NAME)."
    if [[ "\${2:-}" == "-y" || "\${2:-}" == "--yes" || "\${2:-}" == "-f" || "\${2:-}" == "--force" ]]; then
      reply="y"
    else
      read -r -p "Are you sure you want to delete everything including data volumes? [y/N] " reply
    fi
    if [[ "\$reply" =~ ^[Yy] ]]; then
      docker compose --project-name "\$PROJECT_NAME" -f "\$COMPOSE_FILE" down -v --remove-orphans
      echo "Scoreboard stack and data removed."
    else
      echo "Aborted."
    fi
    ;;
  help|-h|--help) usage ;;
  *) usage >&2; exit 2 ;;
esac
EOF
  # Strip any accidental CRLF from generated scripts
  if command -v sed >/dev/null 2>&1; then
    sed -i 's/\r$//' app.sh 2>/dev/null || true
  fi
  chmod +x app.sh 2>/dev/null || true

  printf '  %s✓ Created control script:%s ./app.sh\n\n' "$GREEN" "$RESET"
}

# Helper: ensure node, npm, and node_modules dependencies (tsc, vite, esbuild) are ready
_ensure_node_dependencies() {
  say "Checking Node.js environment and project dependencies..."

  if ! command -v node >/dev/null 2>&1 || ! command -v npm >/dev/null 2>&1; then
    warn "Node.js and npm are required for this mode but were not found in PATH."
    say "Please install Node.js (>= 20) and npm first: https://nodejs.org/"
    exit 1
  fi

  local need_install=0
  if [[ ! -d "node_modules" || ! -f "node_modules/.bin/tsc" || ! -f "node_modules/.bin/vite" ]]; then
    need_install=1
  fi

  if (( need_install )); then
    step "Dependencies missing or incomplete. Running npm install..."
    npm install
  fi

  # Verify esbuild execution (in case postinstall scripts were blocked)
  if ! npx esbuild --version >/dev/null 2>&1; then
    warn "esbuild binary is not executable (postinstall scripts may have been blocked)."
    step "Rebuilding native binary packages (npm rebuild esbuild)..."
    npm rebuild esbuild || npm install --ignore-scripts=false
  fi

  # If Cloudflare mode requires wrangler
  if [[ "${1:-}" == "wrangler" ]]; then
    if ! npx wrangler --version >/dev/null 2>&1; then
      step "Installing Wrangler CLI (npm install -D wrangler)..."
      npm install -D wrangler
      npm rebuild workerd >/dev/null 2>&1 || true
    fi
  fi

  printf '  %s✓ Node.js dependencies and binaries (tsc, vite) are ready.%s\n\n' "$GREEN" "$RESET"
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
PROJECT_NAME="app_scoreboard"

banner "BewerbsBoard Setup & Deployment Wizard"

# ── Stage 0: Mode Selection (Demo vs Deploy) ───────────────────────────────
stage "Choose Mode — Demo vs Full Deployment"
say "Select how you would like to run BewerbsBoard:"
printf '\n'
say "  [1] Demo Mode (Launch instant local dev server with preview links)"
say "  [2] Deploy Application (Local Docker, Cloudflare Pages, or Keycloak/Proxy)"
printf '\n'

ask MODE_CHOICE "Enter selection [1/2] (default: 2):"
if [[ "$MODE_CHOICE" == "1" ]]; then
  stage "Demo Mode — Project Setup & Dev Server"
  _ensure_node_dependencies

  say "Starting local development server..."
  step "Running: npm run dev"

  printf '\n%s  Demo preview URLs:%s\n' "$BOLD" "$RESET"
  printf '  • %sPublic Scoreboard:%s http://localhost:5173/?demo=true\n' "$GREEN" "$RESET"
  printf '  • %sAdmin Dashboard:%s   http://localhost:5173/admin?demo=true\n' "$GREEN" "$RESET"
  printf '  • %sTV Display (Theme 1):%s http://localhost:5173/tv?theme=1&demo=true\n' "$GREEN" "$RESET"
  printf '  • %sTV Display (Theme 2):%s http://localhost:5173/tv?theme=2&demo=true\n\n' "$GREEN" "$RESET"

  if confirm "Open Admin & TV pages in browser now?"; then
    open_url "http://localhost:5173/admin?demo=true"
    open_url "http://localhost:5173/tv?theme=1&demo=true"
  fi

  say "Starting dev server (Press Ctrl+C to stop when done)..."
  npm run dev
  exit 0
fi

# ── Stage 1: Deployment Target Selection ──────────────────────────────────
stage "Deployment Target Selection"
say "Select your deployment environment:"
printf '\n'
say "  [1] Local Only (Standalone Docker Compose with built-in username/password auth)"
say "  [2] Cloudflare Pages (Serverless deployment with D1 database & KV storage)"
say "  [3] Local Docker + Reverse Proxy + Keycloak OIDC (via oauth2-proxy)"
printf '\n'

ask DEPLOY_TARGET "Enter target option [1/2/3] (default: 1):"
[[ -z "$DEPLOY_TARGET" ]] && DEPLOY_TARGET="1"

# ══════════════════════════════════════════════════════════════════════════
# BRANCH 1: Local Only (Docker Compose with Local Auth)
# ══════════════════════════════════════════════════════════════════════════
if [[ "$DEPLOY_TARGET" == "1" ]]; then
  TOTAL_STAGES=6
  stage "Local Docker — Server Port & Network Preflight"
  say "Configure host bind address and listening port."
  
  ask APP_BIND_ADDRESS "Enter host bind address (default: 0.0.0.0):"
  [[ -z "$APP_BIND_ADDRESS" ]] && APP_BIND_ADDRESS="0.0.0.0"
  write_env APP_BIND_ADDRESS "$APP_BIND_ADDRESS"

  ask APP_PORT "Enter host port (default: 3080):"
  [[ -z "$APP_PORT" ]] && APP_PORT="3080"
  
  while ! _check_port_available "$APP_PORT"; do
    warn "Port $APP_PORT is currently in use by another process!"
    if confirm "Would you like to choose a different port?"; then
      ask APP_PORT "Enter an alternative port number:"
    else
      warn "Proceeding with port $APP_PORT (warning: container may fail to bind)."
      break
    fi
  done
  write_env APP_PORT "$APP_PORT"

  stage "Local Docker — Authentication Credentials"
  say "Configure built-in local administrator credentials."
  
  ask LOCAL_AUTH_USER "Enter admin username (default: admin):"
  [[ -z "$LOCAL_AUTH_USER" ]] && LOCAL_AUTH_USER="admin"
  write_env LOCAL_AUTH_USER "$LOCAL_AUTH_USER"

  ask_secret LOCAL_AUTH_PASSWORD "Enter admin password:"
  while [[ -z "$LOCAL_AUTH_PASSWORD" ]]; do
    warn "Password cannot be empty."
    ask_secret LOCAL_AUTH_PASSWORD "Enter admin password:"
  done
  write_env LOCAL_AUTH_PASSWORD "$LOCAL_AUTH_PASSWORD"

  ask_secret LOCAL_AUTH_SECRET "Enter cookie secret (press Enter to auto-generate):"
  if [[ -z "$LOCAL_AUTH_SECRET" ]]; then
    LOCAL_AUTH_SECRET=$(_generate_random_secret)
  fi
  write_env LOCAL_AUTH_SECRET "$LOCAL_AUTH_SECRET"

  stage "Local Docker — Host Network Info Collector (Optional)"
  say "To display host interface names and addresses in the TV admin splash,"
  say "a systemd collector service can be installed on the Linux Docker host."
  
  COMPOSE_ARGS="-f compose.yaml"
  
  if confirm "Install the host network info collector? (requires sudo)"; then
    step "Installing network-info-writer.sh to /usr/local/lib/bewerbsboard..."
    sudo install -Dm755 deploy/network-info-writer.sh /usr/local/lib/bewerbsboard/network-info-writer.sh
    step "Installing and enabling systemd service..."
    sudo install -Dm644 deploy/bewerbsboard-network-info.service /etc/systemd/system/bewerbsboard-network-info.service
    sudo systemctl daemon-reload
    sudo systemctl enable --now bewerbsboard-network-info.service
    
    COMPOSE_ARGS="-f compose.yaml -f compose.network-info.yaml"
    say "Added compose.network-info.yaml to the deployment configuration."
  fi

  stage "Local Docker — Compose Deployment"
  say "Building and launching Docker container..."
  step "Running: docker compose --project-name $PROJECT_NAME $COMPOSE_ARGS up -d --build --wait"

  docker compose --project-name "$PROJECT_NAME" $COMPOSE_ARGS up -d --build --wait

  stage "Healthcheck & Verification"
  say "Verifying application status..."
  HEALTHCHECK_HOST="$APP_BIND_ADDRESS"
  [[ "$HEALTHCHECK_HOST" == "0.0.0.0" ]] && HEALTHCHECK_HOST="127.0.0.1"
  HEALTH_URL="http://${HEALTHCHECK_HOST}:${APP_PORT}/healthz"

  if command -v curl >/dev/null 2>&1; then
    if curl --fail --silent --show-error "$HEALTH_URL" >/dev/null; then
      printf '  %s✓ Healthcheck passed at %s%s\n' "$GREEN" "$HEALTH_URL" "$RESET"
    else
      warn "Healthcheck request failed at $HEALTH_URL"
    fi
  fi

  _generate_control_scripts "$COMPOSE_ARGS"

  finish
  DISPLAY_HOST="$APP_BIND_ADDRESS"
  if [[ "$DISPLAY_HOST" == "0.0.0.0" ]]; then
    if command -v ip >/dev/null 2>&1; then
      LAN_IP=$(ip -o addr show scope global 2>/dev/null | awk '$3 == "inet" && $2 !~ /^(docker|br-|veth|cni|tun|tap|lo)/ { split($4, a, "/"); print a[1]; exit }')
      if [[ -n "$LAN_IP" ]]; then
        DISPLAY_HOST="$LAN_IP"
      else
        DISPLAY_HOST="127.0.0.1"
      fi
    else
      DISPLAY_HOST="127.0.0.1"
    fi
  fi

  printf '%s  Admin Login:%s http://%s:%s/admin (User: %s)\n' "$GREEN" "$RESET" "$DISPLAY_HOST" "$APP_PORT" "$LOCAL_AUTH_USER"
  printf '%s  TV Display:%s  http://%s:%s/tv?theme=1\n\n' "$GREEN" "$RESET" "$DISPLAY_HOST" "$APP_PORT"
  say "Quick management commands:"
  say "  • Start:  ./app.sh start"
  say "  • Stop:   ./app.sh stop"
  say "  • Delete: ./app.sh delete"
  printf '\n'
  exit 0
fi

# ══════════════════════════════════════════════════════════════════════════
# BRANCH 2: Cloudflare Pages + D1 + KV Deployment
# ══════════════════════════════════════════════════════════════════════════
if [[ "$DEPLOY_TARGET" == "2" ]]; then
  stage "Cloudflare — Project Setup & Wrangler Verification"
  _ensure_node_dependencies "wrangler"

  step "Authenticating with Cloudflare (opens browser login)..."
  npx wrangler login

  stage "Cloudflare — Provision D1 Database & KV Namespace"
  say "Creating remote database and key-value namespace."
  
  step "Creating D1 database: bewerbsboard"
  npx wrangler d1 create bewerbsboard || true
  say "If a new database_id was generated above, ensure it is set in wrangler.toml under [[d1_databases]]."
  pause "Press Enter after confirming wrangler.toml..."

  step "Creating KV namespace: KV"
  npx wrangler kv namespace create KV || true
  say "If a new KV namespace id was generated above, ensure it is set in wrangler.toml under [[kv_namespaces]]."
  pause "Press Enter after confirming wrangler.toml..."

  stage "Cloudflare Pages — Project & Migration"
  ask PAGES_PROJECT_NAME "Enter Cloudflare Pages project name (default: bewerbsboard):"
  [[ -z "$PAGES_PROJECT_NAME" ]] && PAGES_PROJECT_NAME="bewerbsboard"

  step "Creating Pages project ($PAGES_PROJECT_NAME)..."
  npx wrangler pages project create "$PAGES_PROJECT_NAME" --production-branch main || true

  step "Applying remote D1 database migrations..."
  npm run db:migrate:remote

  stage "Cloudflare Pages — Build & Deploy"
  step "Building production bundle (npm run build)..."
  npm run build

  step "Deploying to Cloudflare Pages..."
  npx wrangler pages deploy dist --project-name "$PAGES_PROJECT_NAME"

  finish
  say "Cloudflare Pages deployment complete!"
  exit 0
fi

# ══════════════════════════════════════════════════════════════════════════
# BRANCH 3: Local Docker + Keycloak OIDC + oauth2-proxy + Reverse Proxy
# ══════════════════════════════════════════════════════════════════════════
if [[ "$DEPLOY_TARGET" == "3" ]]; then
  stage "Keycloak OIDC Configuration Instructions"
  say "Set up a client in your Keycloak Admin Console:"
  step "1. In Keycloak Admin: Select your Realm (e.g. 'homelab')."
  step "2. Go to 'Clients' → 'Create Client'."
  step "3. Set Client type: OpenID Connect, Client ID: bewerb-oauth2-proxy."
  step "4. Enable 'Client authentication' (Confidential client)."
  step "5. Under Valid redirect URIs: add 'https://<your-domain>/oauth2/callback'."
  step "6. Under Credentials tab: copy the generated 'Client Secret'."
  pause "Press Enter when you have your Keycloak details ready..."

  stage "Keycloak & Proxy Credentials (.env)"
  ask OAUTH2_PROXY_OIDC_ISSUER_URL "Enter Keycloak Issuer URL (e.g. https://keycloak.example.com/realms/homelab):"
  while [[ -z "$OAUTH2_PROXY_OIDC_ISSUER_URL" ]]; do
    warn "Keycloak Issuer URL is required."
    ask OAUTH2_PROXY_OIDC_ISSUER_URL "Enter Keycloak Issuer URL:"
  done
  write_env OAUTH2_PROXY_OIDC_ISSUER_URL "$OAUTH2_PROXY_OIDC_ISSUER_URL"

  ask OAUTH2_PROXY_CLIENT_ID "Enter Keycloak Client ID (default: bewerb-oauth2-proxy):"
  [[ -z "$OAUTH2_PROXY_CLIENT_ID" ]] && OAUTH2_PROXY_CLIENT_ID="bewerb-oauth2-proxy"
  write_env OAUTH2_PROXY_CLIENT_ID "$OAUTH2_PROXY_CLIENT_ID"

  ask_secret OAUTH2_PROXY_CLIENT_SECRET "Enter Keycloak Client Secret:"
  while [[ -z "$OAUTH2_PROXY_CLIENT_SECRET" ]]; do
    warn "Client Secret cannot be empty."
    ask_secret OAUTH2_PROXY_CLIENT_SECRET "Enter Keycloak Client Secret:"
  done
  write_env OAUTH2_PROXY_CLIENT_SECRET "$OAUTH2_PROXY_CLIENT_SECRET"

  ask_secret OAUTH2_PROXY_COOKIE_SECRET "Enter Proxy Cookie Secret (press Enter to auto-generate 32-byte secret):"
  if [[ -z "$OAUTH2_PROXY_COOKIE_SECRET" ]]; then
    OAUTH2_PROXY_COOKIE_SECRET=$(_generate_random_secret)
  fi
  write_env OAUTH2_PROXY_COOKIE_SECRET "$OAUTH2_PROXY_COOKIE_SECRET"

  ask APP_BIND_ADDRESS "Enter host bind address (default: 0.0.0.0):"
  [[ -z "$APP_BIND_ADDRESS" ]] && APP_BIND_ADDRESS="0.0.0.0"
  write_env APP_BIND_ADDRESS "$APP_BIND_ADDRESS"

  ask APP_PORT "Enter Scoreboard app host port (default: 3080):"
  [[ -z "$APP_PORT" ]] && APP_PORT="3080"
  while ! _check_port_available "$APP_PORT"; do
    warn "Port $APP_PORT is in use!"
    ask APP_PORT "Enter an alternative port:"
  done
  write_env APP_PORT "$APP_PORT"

  ask OAUTH2_PROXY_PORT "Enter oauth2-proxy host port (default: 4180):"
  [[ -z "$OAUTH2_PROXY_PORT" ]] && OAUTH2_PROXY_PORT="4180"
  while ! _check_port_available "$OAUTH2_PROXY_PORT"; do
    warn "Port $OAUTH2_PROXY_PORT is in use!"
    ask OAUTH2_PROXY_PORT "Enter an alternative oauth2-proxy port:"
  done
  write_env OAUTH2_PROXY_PORT "$OAUTH2_PROXY_PORT"

  stage "Reverse Proxy Selection"
  say "How will Nginx / Reverse Proxy be handled?"
  printf '\n'
  say "  [1] I already have an external reverse proxy (Show Nginx configuration snippet)"
  say "  [2] Deploy integrated Nginx container inside Docker Compose"
  printf '\n'
  ask REVERSE_PROXY_CHOICE "Enter selection [1/2] (default: 1):"
  [[ -z "$REVERSE_PROXY_CHOICE" ]] && REVERSE_PROXY_CHOICE="1"

  # Generate compose.keycloak.yaml
  step "Generating compose.keycloak.yaml with oauth2-proxy service..."
  cat <<'EOF' > compose.keycloak.yaml
name: web-scoreboard-local

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    restart: unless-stopped
    ports:
      - "${APP_BIND_ADDRESS:-0.0.0.0}:${APP_PORT:-3080}:8080"
    env_file:
      - path: .env
        required: false
    volumes:
      - type: volume
        source: scoreboard-data
        target: /app/data
    read_only: true
    tmpfs:
      - /tmp:size=16m,mode=1777
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    pids_limit: 256
    cpus: 1
    mem_limit: 768m
    healthcheck:
      test: ["CMD", "node", "/app/server/healthcheck.mjs"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2-proxy
    restart: unless-stopped
    ports:
      - "${APP_BIND_ADDRESS:-0.0.0.0}:${OAUTH2_PROXY_PORT:-4180}:4180"
    environment:
      OAUTH2_PROXY_PROVIDER: "keycloak-oidc"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "${OAUTH2_PROXY_OIDC_ISSUER_URL}"
      OAUTH2_PROXY_CLIENT_ID: "${OAUTH2_PROXY_CLIENT_ID}"
      OAUTH2_PROXY_CLIENT_SECRET: "${OAUTH2_PROXY_CLIENT_SECRET}"
      OAUTH2_PROXY_COOKIE_SECRET: "${OAUTH2_PROXY_COOKIE_SECRET}"
      OAUTH2_PROXY_COOKIE_SECURE: "true"
      OAUTH2_PROXY_COOKIE_SAMESITE: "lax"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_UPSTREAMS: "static://202"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
EOF

  if [[ "$REVERSE_PROXY_CHOICE" == "2" ]]; then
    ask NGINX_HTTP_PORT "Enter Nginx external HTTP port (default: 80):"
    [[ -z "$NGINX_HTTP_PORT" ]] && NGINX_HTTP_PORT="80"

    # Create deploy/nginx.conf for container
    mkdir -p deploy
    cat <<EOF > deploy/nginx.conf
events {}
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    proxy_buffer_size 16k;
    proxy_buffers 4 32k;
    proxy_busy_buffers_size 64k;

    server {
        listen 80;
        
        location /oauth2/ {
            proxy_pass http://oauth2-proxy:4180;
            proxy_set_header Host \$host;
            proxy_set_header X-Real-IP \$remote_addr;
            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto \$scheme;
            proxy_set_header X-Auth-Request-Redirect \$request_uri;
        }

        location = /oauth2/auth {
            proxy_pass http://oauth2-proxy:4180/oauth2/auth;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header Host \$host;
            proxy_set_header X-Real-IP \$remote_addr;
            proxy_set_header X-Forwarded-Proto \$scheme;
            proxy_set_header X-Forwarded-Uri \$request_uri;
        }

        location @oauth2_signin {
            return 302 /oauth2/sign_in?rd=\$request_uri;
        }

        location /admin {
            auth_request /oauth2/auth;
            error_page 401 = @oauth2_signin;
            auth_request_set \$authenticated_email \$upstream_http_x_auth_request_email;
            auth_request_set \$authenticated_user \$upstream_http_x_auth_request_user;
            proxy_set_header X-Auth-Request-Email \$authenticated_email;
            proxy_set_header X-Auth-Request-User \$authenticated_user;
            proxy_pass http://app:8080;
        }

        location /api/admin/ {
            auth_request /oauth2/auth;
            auth_request_set \$authenticated_email \$upstream_http_x_auth_request_email;
            proxy_set_header X-Auth-Request-Email \$authenticated_email;
            proxy_pass http://app:8080;
        }

        location / {
            proxy_set_header X-Auth-Request-Email "";
            proxy_pass http://app:8080;
        }
    }
}
EOF

    # Add nginx service to compose.keycloak.yaml
    cat <<EOF >> compose.keycloak.yaml

  nginx:
    image: nginx:alpine
    container_name: scoreboard-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_PORT}:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - oauth2-proxy
EOF
  fi

  # Append top-level volumes definition
  cat <<'EOF' >> compose.keycloak.yaml

volumes:
  scoreboard-data:
EOF

  stage "Docker Compose Deployment"
  say "Building and starting container stack (app + oauth2-proxy)..."
  step "Running: docker compose --project-name $PROJECT_NAME -f compose.keycloak.yaml up -d --build --wait"
  docker compose --project-name "$PROJECT_NAME" -f compose.keycloak.yaml up -d --build --wait

  stage "Healthcheck & Multi-Point Verification"
  say "Verifying deployment endpoints..."

  CHECK_HOST="$APP_BIND_ADDRESS"
  [[ "$CHECK_HOST" == "0.0.0.0" ]] && CHECK_HOST="127.0.0.1"

  # 1. Scoreboard App
  printf '\n  [1] Scoreboard App Healthcheck (/healthz): '
  if curl --fail --silent --show-error "http://${CHECK_HOST}:${APP_PORT}/healthz" >/dev/null 2>&1; then
    printf '%s✓ OK%s\n' "$GREEN" "$RESET"
  else
    printf '%s✗ FAILED%s\n' "$RED" "$RESET"
  fi

  # 2. oauth2-proxy
  printf '  [2] oauth2-proxy endpoint (:4180/ping):   '
  if curl --silent --show-error "http://${CHECK_HOST}:${OAUTH2_PROXY_PORT}/ping" 2>&1 | grep -q "OK"; then
    printf '%s✓ OK%s\n' "$GREEN" "$RESET"
  else
    printf '%s⚠ Note: ping response checked%s\n' "$YELLOW" "$RESET"
  fi

  # 3. Keycloak Issuer
  printf '  [3] Keycloak OIDC OpenID Config:         '
  if curl --fail --silent --show-error "${OAUTH2_PROXY_OIDC_ISSUER_URL}/.well-known/openid-configuration" >/dev/null 2>&1; then
    printf '%s✓ Reachable%s\n' "$GREEN" "$RESET"
  else
    printf '%s⚠ Warning: Issuer URL not reachable directly from this host%s\n' "$YELLOW" "$RESET"
  fi

  if [[ "$REVERSE_PROXY_CHOICE" == "1" ]]; then
    printf '\n%s  Nginx Configuration for your external reverse proxy:%s\n' "$BOLD" "$RESET"
    note "Copy the following snippet into your TLS server block in Nginx:"
    printf '\n'
    cat <<EOF
# --- Nginx snippet for BewerbsBoard + oauth2-proxy ---
proxy_buffer_size 16k;
proxy_buffers 4 32k;
proxy_busy_buffers_size 64k;

location /oauth2/ {
    proxy_pass http://${CHECK_HOST}:${OAUTH2_PROXY_PORT};
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Auth-Request-Redirect \$request_uri;
}

location = /oauth2/auth {
    proxy_pass http://${CHECK_HOST}:${OAUTH2_PROXY_PORT}/oauth2/auth;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-Uri \$request_uri;
}

location @oauth2_signin {
    return 302 /oauth2/sign_in?rd=\$request_uri;
}

location /admin {
    auth_request /oauth2/auth;
    error_page 401 = @oauth2_signin;
    auth_request_set \$authenticated_email \$upstream_http_x_auth_request_email;
    proxy_set_header X-Auth-Request-Email \$authenticated_email;
    proxy_pass http://${CHECK_HOST}:${APP_PORT};
}

location /api/admin/ {
    auth_request /oauth2/auth;
    auth_request_set \$authenticated_email \$upstream_http_x_auth_request_email;
    proxy_set_header X-Auth-Request-Email \$authenticated_email;
    proxy_pass http://${CHECK_HOST}:${APP_PORT};
}

location / {
    proxy_set_header X-Auth-Request-Email "";
    proxy_pass http://${CHECK_HOST}:${APP_PORT};
}
EOF
  fi

  _generate_control_scripts "compose.keycloak.yaml"

  finish
  say "Deployment stack with Keycloak and oauth2-proxy is ready."
  printf '\n'
  say "Quick management commands:"
  say "  • Start:  ./app.sh start"
  say "  • Stop:   ./app.sh stop"
  say "  • Delete: ./app.sh delete"
  printf '\n'
  exit 0
fi

finish
