/**
 * Static, user-facing application copy.
 *
 * Keep visible UI text and accessibility descriptions here. Domain data,
 * routes, technical identifiers, and user-provided content stay with their
 * owning modules.
 */

import { authText } from './auth-text';
export { authText };

export const commonText = {
  brandMark: 'BB',
  productName: 'BewerbsBoard',
  scoreboard: 'BewerbsBoard',
  adminBadge: 'ADMIN',
  logout: 'Abmelden',
} as const;

export const adminLayoutText = {
  audienceView: 'Zuschaueransicht',
  tvDisplay: 'TV-Anzeige',
  navigationLabel: 'Admin Navigation',
  openMenu: 'Menü',
  closeMenu: 'Menü schließen',
  moduleTitle: (label: string) => `${label} Modul`,
  readyForTicketImplementation: 'Bereit für Ticket-Implementierung',
  footer: (year: number) =>
    `BewerbsBoard © ${year} — Cloudflare Pages & D1 Competition Engine`,
} as const;

export const adminTabsText = {
  results: {
    label: 'Erfassung',
    description: 'Direkte Erfassung von Angriffzeiten und Fehlerpunkten.',
  },
  participants: {
    label: 'Teilnehmer',
    description: 'Verwaltung der teilnehmenden Gruppen und Startreihenfolge.',
  },
  broadcast: {
    label: 'TV-Steuerung',
    description: 'Steuerung der Live-Hallenanzeigen: Moduswahl & Durchsagen.',
  },
  setup: {
    label: 'Bewerbs-Setup',
    description: 'Verwaltung von Wertungsklassen, Kategorien und Wertungen.',
  },
  settings: {
    label: 'Einstellungen',
    description: 'Globaler Bewerbsname, Design und Zuschauer-Zugriff.',
  },
  logs: {
    label: 'Logs & Status',
    description: 'Systemstatus, Datenbank-Gesundheit und Audit-Protokoll.',
  },
} as const;

export const publicScoreboardText = {
  defaultCompetitionTitle: 'Feuerwehr Leistungsbewerb',
  livePolling: 'LIVE UPDATE (5s)',
  combinedRanking: 'Kombinierte Wertung',
  relayRanking: 'Wertung mit Staffellauf',
  standardRanking: 'Standard-Wertung',
  evaluatedCount: (count: number) => `${count} Gewertet`,
  openCount: (count: number) => `${count} Offen`,
  rank: 'Rang',
  group: 'Gruppe',
  groupName: (groupName: string) => `Gruppe ${groupName}`,
  attack: 'Angriff',
  attackShort: 'ANG',
  relay: 'Staffellauf',
  relayShort: 'SL',
  total: 'Gesamt',
  totalTime: 'Gesamtzeit',
  defaultDiscipline1: 'Disziplin 1',
  defaultDiscipline2: 'Disziplin 2',
  disciplineLabel: (categoryName: string, discipline: string) => `${categoryName} ${discipline}`,
  noResultsEntered: 'Noch keine Ergebnisse eingetragen',
  resultsLoadError: (status: number) =>
    `Fehler beim Laden der Ergebnisse (${status})`,
  resultsCouldNotBeLoaded: 'Ergebnisse konnten nicht geladen werden',
  loadingResults: 'Lade Bewerbsergebnisse...',
  loadingErrorTitle: 'Fehler beim Laden',
  retry: 'Erneut versuchen',
  lastUpdated: (time: string) => `Stand: ${time}`,
  rankingList: 'Wertungsliste',
  noRankedTimes: 'Noch keine gewerteten Zeiten vorhanden',
  upcomingStarts: 'Nächste Starts',
  noPendingRuns: 'Keine weiteren Läufe ausstehend',
  disqualified: 'Disqualifiziert (DNF)',
  dnf: 'DNF',
  footer: (year: number) =>
    `© ${year} BewerbsBoard • Live Spectator Portal`,
} as const;

export const tvText = {
  results: 'Ergebnisse',
  connecting: 'Verbinde mit Server...',
  disconnected: 'Verbindung unterbrochen',
  interimResult: 'Zwischenstand',
  identityRegion: 'Identity Rail',
  eventLogoAlt: 'Veranstaltungslogo',
  ranking: (categoryName: string) => `${categoryName} Wertung`,
  noActiveCategory: 'Keine Kategorie für TV-Anzeige aktiv',
  noResults: 'Noch keine Ergebnisse in dieser Kategorie',
  winnersTitle: 'Siegerehrung',
  unknownFireBrigade: 'Unbekannte Feuerwehr',
  noAnnouncement: 'Keine Durchsage konfiguriert',
  rank: 'Rang',
  participant: 'Feuerwehr / Gruppe',
  fireBrigade: 'Feuerwehr',
  groupName: (groupName: string) => `Gruppe ${groupName}`,
  time: 'Zeit',
  attack: 'Angriff',
  attackShort: 'ANG',
  relay: 'Staffellauf',
  relayShort: 'SL',
  total: 'Gesamt',
  dnf: 'DNF',
  defaultDiscipline1: 'Disziplin 1',
  defaultDiscipline2: 'Disziplin 2',
  disciplineLabel: (categoryName: string, discipline: string) => `${categoryName} ${discipline}`,
  qr: {
    regionLabel: 'Scan Panel',
    liveResults: 'Live-Ergebnisse',
    codeTitle: 'Live-Ergebnisse QR-Code',
    scanHint: 'QR-Code scannen für Live-Wertungen',
  },
  adminSplash: {
    badge: 'Ersteinrichtung & Administration',
    title: 'Scoreboard Administration',
    accessPrompt: 'Admin-Dashboard aufrufen:',
    accessUrl: (url: string) => `Access Admin Dashboard on ${url}`,
    qrHint: 'QR-Code scannen, um das Admin-Dashboard direkt auf dem Smartphone, Tablet oder Laptop zu öffnen.',
    dismissHint: 'Dieser Einrichtungs-Hinweis kann im Admin-Dashboard unter „Einstellungen" oder „TV-Steuerung" deaktiviert werden.',
    networkInterfaces: 'Erkannte Netzwerk-Adressen (LAN / WLAN):',
    statusReady: 'System bereit für Bewerbserfassung & Steuerung',
  },
  themes: {
    broadcast: { label: 'Broadcast', summary: 'Dunkel, formal und auf die Wertung fokussiert.' },
    ceremony: { label: 'Ceremony', summary: 'Warm, festlich und auf den Veranstaltungscharakter ausgerichtet.' },
    outdoor: { label: 'Outdoor Light', summary: 'Hell und kontrastreich — optimiert für Außendisplays bei Sonnenlicht.' },
  },
} as const;

export const resultsText = {
  loadDataError: 'Fehler beim Laden der Zeiterfassungs-Daten',
  loadError: 'Fehler beim Laden',
  saveError: 'Fehler beim Speichern',
  statusError: 'Fehler beim Ändern des Status',
  allCategories: 'Alle Kategorien',
  openCount: (count: number) => `${count} Offen`,
  validCount: (count: number) => `${count} Gültig`,
  dnfCount: (count: number) => `${count} DNF`,
  loading: 'Lade Zeiterfassung...',
  openRunsTitle: 'Aktive Startreihenfolge (Offene Läufe)',
  autoValidBefore: 'Eingabe von Zeit + Fehlerpunkten schaltet den Lauf automatisch auf',
  validStatus: 'GÜLTIG',
  autoValidAfter: 'um.',
  noOpenRuns: 'Keine offenen Läufe in dieser Kategorie.',
  attackTime: 'Angriffszeit (s)',
  attackTimePlaceholder: '60,00',
  errors: 'Fehler',
  errorsPlaceholder: '0',
  relayTime: 'Staffellaufzeit (s)',
  relayTimePlaceholder: '60,00',
  relayErrors: 'Staffelfehler',
  dnf: 'DNF',
  saving: 'Speichert...',
  save: 'Speichern',
  validRankingsTitle: 'Gültige Wertungen & Rangliste',
  noValidRuns: 'Noch keine gültigen Läufe erfasst.',
  attackAndRelay: 'Angriff / Staffel',
  totalTime: 'Gesamtzeit',
  resetToOpenTitle: 'Wertung zurücknehmen',
  resetToOpen: 'Zurücknehmen',
  disqualifiedTitle: 'Disqualifiziert / DNF',
} as const;

export const participantsText = {
  startOrder: 'Startreihenfolge',
  masterData: 'Stammdaten',
  loadError: 'Fehler beim Laden der Stammdaten',
  createBrigadeError: 'Fehler beim Erstellen der Feuerwehr',
  deleteBrigadeError: 'Fehler beim Löschen der Feuerwehr',
  createGroupError: 'Fehler beim Erstellen der Gruppe',
  deleteGroupError: 'Fehler beim Löschen der Gruppe',
  genericError: 'Fehler',
  deleteBrigadeConfirm: (name: string) => `Möchten Sie die Feuerwehr "${name}" wirklich löschen?`,
  deleteGroupConfirm: (name: string) => `Möchten Sie die Gruppe "${name}" wirklich löschen?`,
  noCompetitionClass: 'Keine Wertungsklasse verfügbar',
  duplicateGroup: 'Diese Gruppe ist für die gewählte Feuerwehr und Wertungsklasse bereits vorhanden.',
  addGroupError: 'Fehler beim erstellen der Gruppe',
  removeEntryError: 'Fehler beim entfernen der Gruppe',
  reorderError: 'Fehler beim neu ordnen',
  unknownError: 'Unbekannter Fehler',
  loadingMasterData: 'Laden der Stammdaten...',
  errorPrefix: '⚠️ Fehler:',
  close: 'Schließen',
  relay: 'Staffel',
  withoutRelay: 'Ohne Staffel',
  groupsInCategory: (name: string) => `Gruppen in ${name}`,
  relayRace: 'Staffellauf:',
  available: '✓ Vorhanden',
  noRelayRace: '✕ Kein Staffellauf',
  selectGroup: 'Gruppe auswählen...',
  noAvailableGroups: 'Keine verfügbaren Gruppen',
  adding: 'Wird hinzugefügt...',
  add: 'Hinzufügen',
  loadingStartList: 'Lade Startliste...',
  noGroupsRegistered: 'Noch keine Gruppen in dieser Kategorie gemeldet.',
  status: 'Status:',
  moveUp: 'Nach oben verschieben',
  moveDown: 'Nach unten verschieben',
  removeEntry: 'Eintrag entfernen',
  noSetup: 'Keine Bewerbsklassen konfiguriert. Bitte legen Sie zuerst Kategorien in Bewerbs-Setup an.',
  brigades: 'Feuerwehren',
  brigadesDescription: 'Feuerwehren verwalten und registrieren.',
  brigadeNamePlaceholder: 'Name der Feuerwehr',
  name: 'Name',
  groups: 'Gruppen',
  actions: 'Aktionen',
  groupCount: (count: number) => `${count} ${count === 1 ? 'Gruppe' : 'Gruppen'}`,
  delete: 'Löschen',
  noBrigades: 'Keine Feuerwehren vorhanden.',
  groupsDescription: 'Bewerbsgruppen mit Wertungsklasse anlegen und verwalten.',
  selectBrigadeLabel: 'Feuerwehr auswählen',
  selectBrigade: '-- Feuerwehr wählen --',
  groupNamePlaceholder: 'Gruppenname (z.B. 1)',
  selectCompetitionClass: 'Wertungsklasse auswählen',
  createGroup: 'Gruppe anlegen',
  brigade: 'Feuerwehr',
  group: 'Gruppe',
  competitionClass: 'Wertungsklasse',
  unknown: 'Unbekannt',
  noGroups: 'Keine Gruppen vorhanden.',
} as const;

export const setupText = {
  classesAndCategories: 'Klassen & Kategorien',
  rankings: 'Wertungen',
  unknownError: 'Unbekannter Fehler',
  genericError: 'Fehler',
  createClassError: 'Fehler beim Erstellen der Wertungsklasse',
  deleteClassError: 'Fehler beim Löschen der Wertungsklasse',
  deleteClassConfirm: (name: string) => `Möchten Sie die Wertungsklasse "${name}" wirklich löschen?`,
  updateError: (status: number) => `Fehler beim Aktualisieren (${status})`,
  loading: 'Lade Setup-Daten...',
  competitionClasses: 'Wertungsklassen',
  classesDescription: 'Übergeordnete Klassen (z.B. AKTIV, JUGEND, GAST) — werden Bewerbsklassen zugeordnet.',
  classNamePlaceholder: 'Name der Wertungsklasse (z.B. DAMEN)',
  createClass: 'Klasse anlegen',
  competitionClass: 'Wertungsklasse',
  actions: 'Aktionen',
  delete: 'Löschen',
  noClasses: 'Keine Wertungsklassen vorhanden.',
  categoryTypes: {
    createError: (status: number) => `Fehler beim Erstellen der Bewerbskategorie (${status})`,
    created: (name: string) => `Kategorie "${name}" erfolgreich angelegt.`,
    createFallback: 'Fehler beim Erstellen der Bewerbskategorie.',
    emptyName: 'Kategoriename darf nicht leer sein.',
    updated: (name: string) => `Kategorie "${name}" erfolgreich aktualisiert.`,
    updateFallback: 'Fehler beim Aktualisieren der Bewerbskategorie.',
    deleteConfirm: (name: string) => `Möchten Sie die Bewerbskategorie "${name}" wirklich löschen?`,
    deleteError: (status: number) => `Fehler beim Löschen der Bewerbskategorie (${status})`,
    deleted: (name: string) => `Kategorie "${name}" erfolgreich gelöscht.`,
    deleteFallback: 'Fehler beim Löschen der Bewerbskategorie.',
    title: 'Bewerbskategorien',
    description: 'Stammdaten für die grundlegenden Bewerbskategorien (z.B. Bronze Aktiv, Silber Aktiv). Bestimmt, ob ein Staffellauf vorhanden ist.',
    createTitle: 'Neue Bewerbskategorie anlegen',
    categoryName: 'Kategoriename *',
    namePlaceholder: 'z.B. Bronze Aktiv',
    hasRelayRace: 'Staffellauf vorhanden',
    competitionCategory: 'Bewerbsklasse *',
    selectClass: 'Klasse wählen',
    creating: 'Erstelle...',
    create: 'Anlegen',
    name: 'Name',
    competitionClass: 'Bewerbsklasse',
    relayColumn: 'Staffellauf',
    action: 'Aktion',
    empty: 'Keine Bewerbskategorien geladen.',
    categoryNameFor: (name: string) => `Kategoriename für ${name}`,
    save: 'Speichern',
    cancel: 'Abbrechen',
    edit: (name: string) => `Kategorie ${name} bearbeiten`,
    withRelay: '✓ Mit Staffellauf',
    withoutRelay: '✕ Ohne Staffellauf',
    delete: (name: string) => `Kategorie ${name} löschen`,
    deleting: '…',
    deleteButton: '🗑️ Löschen',
  },
  evaluationTypes: {
    selectCategoryError: 'Bitte wählen Sie mindestens eine gültige Kategorie aus.',
    createError: (status: number) => `Fehler beim Erstellen der Wertung (${status})`,
    created: (name: string) => `Wertung "${name}" erfolgreich angelegt.`,
    createFallback: 'Fehler beim Erstellen der Wertung.',
    emptyName: 'Wertungsname darf nicht leer sein.',
    updated: (name: string) => `Wertung "${name}" erfolgreich aktualisiert.`,
    updateFallback: 'Fehler beim Aktualisieren der Wertung.',
    deleteConfirm: (name: string) => `Möchten Sie die Wertung "${name}" wirklich löschen?`,
    deleteError: (status: number) => `Fehler beim Löschen der Wertung (${status})`,
    deleted: (name: string) => `Wertung "${name}" erfolgreich gelöscht.`,
    deleteFallback: 'Fehler beim Löschen der Wertung.',
    title: 'Ergebnis-Wertungen',
    description: 'Konfiguration der Wertungen für Zuschauer- (/) und Hallen-TV-Anzeige (/tv), inkl. Einzel- & Kombinationswertungen sowie TV-Anzeigedauern.',
    enableAllWeb: 'Alle Web ✓',
    enableAllTv: 'Alle TV ✓',
    createTitle: 'Neue Wertung anlegen',
    evaluationName: 'Wertungsname *',
    namePlaceholder: 'z.B. Gesamtwertung Aktiv',
    category1: 'Kategorie 1 *',
    noCategories: 'Keine Kategorien',
    category2: 'Kategorie 2 (optional)',
    noSecondCategory: '-- Keine (Einzelwertung) --',
    excludeRelay: 'Staffellauf ausschließen',
    pairingRequiredTitle: 'Pflichtfeld: Kategorie 1 und 2 gehören zu verschiedenen Wertungsklassen',
    pairingAvailableTitle: 'Besten Ergebnisse der Kategorien werden je Feuerwehr gepaart',
    pairingUnavailableTitle: 'Nur verfügbar wenn Kategorie 2 ausgewählt ist',
    pairing: 'Wehr-Paarung',
    pairingRequired: 'Pflichtfeld – klassen-übergreifend',
    tvDuration: 'TV Dauer:',
    seconds: 'Sek',
    creating: 'Erstelle...',
    create: 'Wertung anlegen',
    name: 'Wertungsname',
    composition: 'Disziplinen / Zusammensetzung',
    web: 'Web (/)',
    tv: 'TV (/tv)',
    duration: 'Dauer (Sek)',
    action: 'Aktion',
    empty: 'Keine Ergebnis-Wertungen angelegt.',
    evaluationNameFor: (name: string) => `Wertungsname für ${name}`,
    save: 'Speichern',
    cancel: 'Abbrechen',
    edit: (name: string) => `Wertung ${name} bearbeiten`,
    pairingTitle: 'Wehr-Paarung: bestes Ergebnis je Feuerwehr wird gepaart',
    pairingBadge: '🔗 Wehr-Paarung',
    withoutRelay: '✕ Ohne Staffel',
    withRelay: '✓ Staffel',
    webVisibility: (name: string) => `Web-Sichtbarkeit für ${name}`,
    webVisibilityTitle: 'In Zuschauer-Webansicht anzeigen',
    tvVisibility: (name: string) => `TV-Sichtbarkeit für ${name}`,
    tvVisibilityTitle: 'In automatischer TV Rotation berücksichtigen',
    tvDurationFor: (name: string) => `TV Anzeigedauer für ${name}`,
    delete: (name: string) => `Wertung ${name} löschen`,
    deleting: '…',
    deleteButton: '🗑️ Löschen',
    showSingleResults: 'Einzelergebnisse anzeigen',
    showSingleResultsTooltip: 'Zeigt auch Gruppen mit nur einem Teilergebnis an (nach vollständigen Wertungen gereiht)',
    showSingleResultsBadge: 'Einzelergebnisse',
    category2For: (name: string) => `Kategorie 2 für ${name}`,
    showSingleResultsFor: (name: string) => `Einzelergebnisse für ${name}`,
  },
} as const;

export const settingsText = {
  generalTab: 'Allgemein & Branding',
  qrTab: 'QR-Code & URL',
  dataTab: 'Datenverwaltung',
  dataManagement: {
    title: 'Daten-Export & Import',
    description: 'Vollständige Sicherung und Wiederherstellung aller Bewerbsdaten, Konfigurationen und Ergebnisse (ohne Audit-Logs und TV-Laufzeitstatus).',
    exportTitle: 'Bewerbsdaten exportieren',
    exportDescription: 'Laden Sie eine vollständige JSON-Sicherungsdatei herunter. Enthält Bewerbsklassen, Wertungskategorien, Wertungsdefinitionen, Feuerwehren, Gruppen, Zeiten und Konfigurationen.',
    exportButton: 'Bewerbsdaten exportieren (JSON)',
    exporting: 'Exportiere...',
    exportSuccess: 'Export erfolgreich gestartet.',
    exportError: (status: number) => `Fehler beim Exportieren (${status})`,
    importTitle: 'Bewerbsdaten importieren',
    importDescription: 'Importieren Sie eine BewerbsBoard-JSON-Datei. Vorhandene Datensätze mit gleicher ID werden aktualisiert, neue Datensätze hinzugefügt. Bei Fehlern wird der gesamte Import zurückgerollt.',
    selectFile: 'JSON-Datei auswählen',
    dragDropHint: 'oder Datei hierher ziehen',
    analyzingFile: 'Prüfe Datei…',
    preflightTitle: 'Vorschau & Validierung vor Import',
    preflightValid: 'Datei gültig und bereit zum Importieren.',
    preflightInvalid: 'Ungültige Datei oder Validierungsfehler.',
    totalEntities: (count: number) => `${count} Datensätze insgesamt`,
    tableHeaderEntity: 'Bereich / Tabelle',
    tableHeaderTotal: 'Gesamt',
    tableHeaderNew: 'Neu anzulegen',
    tableHeaderUpdate: 'Wird aktualisiert',
    entityAppConfig: 'System- & Bewerbs-Konfiguration',
    entityCompetitionClasses: 'Wertungsklassen (Klassen)',
    entityFireBrigades: 'Feuerwehren',
    entityCategoryTypes: 'Bewerbsdisziplinen (Kategorien)',
    entityEvaluationTypes: 'Wertungsdefinitionen (Rankings)',
    entityGroups: 'Teilnehmende Gruppen',
    entityCategoryEntries: 'Ergebnisse & Startzeiten',
    importButton: 'Import jetzt anwenden',
    importing: 'Importiere...',
    importSuccess: 'Daten erfolgreich importiert!',
    importError: (msg: string) => `Fehler beim Import: ${msg}`,
    cancel: 'Abbrechen / Andere Datei wählen',
    warningNote: 'Hinweis: Vorhandene Datensätze mit übereinstimmender ID werden überschrieben. Nicht in der Datei enthaltene Daten bleiben unverändert.',
  },
  loadError: (status: number) => `Fehler beim Laden der Einstellungen (${status})`,
  loadFallback: 'Einstellungen konnten nicht geladen werden.',
  saveError: (status: number) => `Fehler beim Speichern (${status})`,
  saveFallback: 'Fehler beim Speichern der Einstellungen.',
  saved: 'Einstellungen erfolgreich gespeichert!',
  discarded: 'Änderungen verworfen.',
  loading: 'Lade Konfiguration...',
  livePreview: 'Live Vorschau: Kopfbereich auf TV (/tv)',
  eventTitlePreviewPlaceholder: 'Bewerbstitel hier eingeben...',
  themePrefix: 'Thema:',
  logoPreviewAlt: 'Veranstaltungslogo Vorschau',
  eventTitle: 'Bewerbsbezeichnung / Titel',
  eventTitlePlaceholder: 'z.B. 72. Landesfeuerwehrleistungsbewerb',
  eventTitleHelp: 'Wird als Hauptüberschrift im Kopfbereich der Zuschaueransicht (/) und des TV-Scoreboards (/tv) angezeigt.',
  tvHeader: 'TV-Kopfzeile',
  tvHeaderPlaceholder: 'Feuerwehr Leistungsbewerb',
  tvHeaderHelp: 'Wird als kleine Beschriftung über dem Veranstaltungstitel im TV-Kopfbereich angezeigt.',
  logoOverride: 'Alternativ-Logo',
  logoPlaceholder: '/branding/logo.svg oder https://…',
  logoHelp: 'Optional: absoluter Pfad auf dieser Website oder eine absolute HTTPS-URL. Standard:',
  logo: {
    title: 'Veranstaltungs-Logo & Wappen',
    description: 'Wählen Sie eine Vorlage oder laden Sie ein individuelles Wappen/Logo hoch. Gespeicherte Logos stehen auch im vollen Offline-Betrieb zur Verfügung.',
    presetSectionTitle: 'Logo-Vorlagen & Auswahl',
    presetDefault: 'Standard',
    presetDefaultDesc: 'Offizielles Bundesfeuerwehrverband-Wappen',
    presetAlt1: 'Alternative 1',
    presetAlt1Desc: 'Modernes Korpsabzeichen Rot/Gold',
    presetAlt2: 'Alternative 2',
    presetAlt2Desc: 'Traditionelles Bundeswappen',
    presetAlt3: 'Alternative 3',
    presetAlt3Desc: 'Klassisches Landesfeuerwehr-Emblem',
    presetCustom: 'Eigenes Logo',
    presetCustomDesc: 'Upload oder URL herunterladen',
    activeBadge: 'Aktiv',
    uploadTitle: 'Eigenes Logo hochladen',
    uploadSubtitle: 'PNG, JPEG, WebP oder SVG (max. 2 MB). Wird direkt für den Offline-Betrieb auf dem Server gespeichert.',
    dropzoneText: 'Bilddatei hierher ziehen oder',
    browseButton: 'Datei auswählen',
    uploading: 'Logo wird hochgeladen…',
    uploadSuccess: 'Logo erfolgreich hochgeladen und aktiviert!',
    uploadError: (msg: string) => `Fehler beim Hochladen: ${msg}`,
    fileTooBig: 'Die Datei überschreitet die maximale Dateigröße von 2 MB.',
    invalidFileType: 'Nicht unterstützter Dateityp. Erlaubt sind PNG, JPEG, WebP und SVG.',
    fetchUrlTitle: 'Logo von Internet-Adresse herunterladen & cachen',
    fetchUrlSubtitle: 'Geben Sie eine Bild-URL ein. Das Bild wird auf den Server heruntergeladen, validiert und offline bereitgestellt.',
    urlPlaceholder: 'https://beispiel.feuerwehr.at/wappen.png',
    fetchButton: 'Herunterladen & Speichern',
    fetching: 'Wird heruntergeladen…',
    fetchSuccess: 'Logo erfolgreich von URL heruntergeladen und gespeichert!',
    fetchError: (msg: string) => `Fehler beim Herunterladen: ${msg}`,
    emptyUrlError: 'Bitte geben Sie eine gültige HTTP- oder HTTPS-URL ein.',
    storedLogoTitle: 'Gespeichertes eigenes Logo',
    storedLogoBadge: 'Offline auf Server gespeichert',
    deleteCustomLogo: 'Eigenes Logo löschen',
    deleting: 'Lösche…',
    deleteSuccess: 'Gespeichertes Logo wurde entfernt. Standard-Logo wieder aktiv.',
    deleteError: (msg: string) => `Fehler beim Löschen des Logos: ${msg}`,
    manualPathTitle: 'Manuelle Pfad- / URL-Eingabe',
    manualPathHelp: 'Alternativ können Sie einen relativen Pfad oder eine HTTPS-URL direkt eingeben.',
    customTabUpload: 'Datei hochladen',
    customTabUrl: 'Von URL abrufen',
  },
  visualTvTheme: 'Visuelles TV-Thema',
  qrTitle: 'QR-Code & Öffentliche Zuschauer-URL',
  qrDescription: 'Zieladresse für den mobilen Zuschauerzugriff und automatische Einblendung des QR-Codes auf den Hallen-TVs.',
  publicUrl: 'Öffentliche Spectator URL',
  publicUrlPlaceholder: 'https://bewerb.feuerwehr.at',
  copyUrlTitle: 'URL in Zwischenablage kopieren',
  copied: 'Kopiert! ✓',
  copyUrl: 'URL kopieren 📋',
  open: 'Öffnen ↗',
  publicUrlHelp: 'Zieladresse für den automatisch generierten QR-Code im Zuschauerportal und dem TV-Overlay.',
  qrOverlayTitle: 'TV-Scoreboard QR-Code Einblendung & Taktung',
  qrOverlayHelp: 'Steuert die zentrierte Einblendung des QR-Codes am oberen Bildschirmrand auf (/tv).',
  enabled: 'Aktiviert (Anzeigen)',
  disabled: 'Deaktiviert (Ausblenden)',
  alwaysVisible: 'Dauerhaft anzeigen (Immer sichtbar)',
  alwaysVisibleHelp: 'ℹ️ Der QR-Code wird dauerhaft oben im TV-Scoreboard eingeblendet. Die Zeitintervalle und die Fortschrittsleiste sind deaktiviert.',
  interval: 'Einblenden alle (Sekunden)',
  intervalHelp: 'Zeitabstand zwischen den QR-Code Einblendungen (z.B. alle 30 Sekunden).',
  duration: 'Anzeigedauer (Sekunden)',
  durationHelp: 'Wie lange der QR-Code jeweils oben im Bildschirm eingeblendet bleibt (z.B. für 10 Sekunden).',
  qrDisabled: 'QR-Code Einblendung ist auf allen TV-Scoreboards vollständig ausgeblendet.',
  adminSplashSection: 'TV-Admin Zugangshinweis & Ersteinrichtung (/tv)',
  adminSplashSectionDescription: 'Steuert, ob auf dem TV-Scoreboard (/tv) der Zugangs-Hinweis mit IP-Adresse und QR-Code für Administratoren angezeigt wird.',
  adminSplashToggle: 'Admin-Zugang auf TV anzeigen',
  adminSplashEnabledLabel: 'Hinweis auf TV aktiv',
  adminSplashDisabledLabel: 'Hinweis auf TV inaktiv',
  adminSplashHelp: 'Zeigt beim Starten oder bei der Ersteinrichtung die IP-Adresse und einen QR-Code auf allen TV-Bildschirmen (/tv) an, um das Admin-Dashboard schnell aufzurufen.',
  detectedIp: 'Erkannte Server-IP:',
  detectedPort: 'Port:',
  adminUrl: 'Admin URL:',
  copyAdminUrl: 'Admin-URL kopieren',
  hideOnTvNow: 'Hinweis auf TV ausblenden',
  showOnTvNow: 'Hinweis auf TV einblenden',
  unsaved: 'Sie haben ungespeicherte Änderungen',
  discard: 'Verwerfen',
  saving: 'Speichere...',
  save: 'Änderungen speichern',
} as const;

export const broadcastText = {
  tvStateError: (status: number) => `TV Status Fehler (${status})`,
  configError: (status: number) => `Config Fehler (${status})`,
  loadFallback: 'Daten konnten nicht geladen werden.',
  updateError: (status: number) => `Fehler beim Aktualisieren (${status})`,
  modeFallback: 'TV Modus konnte nicht aktualisiert werden.',
  announcementSaveError: 'Fehler beim Speichern des Durchsagetenxtes',
  announcementSaved: 'Durchsage gespeichert!',
  announcementFallback: 'Durchsage konnte nicht gespeichert werden.',
  durationRangeError: 'Der Seitenwechsel muss zwischen 1 und 300 Sekunden liegen.',
  configLoadError: 'TV-Konfiguration konnte nicht geladen werden.',
  durationSaveError: 'Seitendauer konnte nicht gespeichert werden.',
  durationSaved: 'Seitendauer gespeichert!',
  adminSplashActiveBanner: 'Auf den TV-Bildschirmen (/tv) wird aktuell der Admin-Zugangs-Hinweis angezeigt.',
  disableSplashButton: 'TV-Scoreboard freigeben (Hinweis ausblenden)',
  loading: 'Lade TV-Steuerung...',
  updating: 'Aktualisiere Anzeige...',
  title: 'Live Hallen-TV Steuerung',
  subtitle: 'Änderungen sind sofort auf allen verbundenen TV-Bildschirmen (/tv) wirksam.',
  settingsTitle: 'TV-Design & QR-Code Einstellungen im Einstellungs-Tab anpassen',
  settings: 'TV-Einstellungen',
  activeMode: 'Aktiver Modus',
  pageDuration: 'Seitenwechsel (Sekunden)',
  pageDurationHelp: 'Legt fest, wie lange eine Ergebnisseite sichtbar bleibt. Diese Dauer ist unabhängig von der Anzeigedauer einer Kategorie.',
  saving: 'Speichert...',
  saveDuration: 'Seitendauer speichern',
  rotation: 'Automatische Rotation',
  rotationHelp: 'Wechselt automatisch durch alle für TV freigegebenen Kategorien basierend auf den konfigurierten Anzeigedauern (Standard 10s).',
  fixed: 'Fixierte Kategorie',
  fixedHelp: 'Friert die Anzeige permanent auf der unten ausgewählten Kategorie ein. Die automatische Rotation wird angehalten.',
  selectCategory: 'Kategorie auswählen',
  pleaseSelect: 'Bitte wählen...',
  winners: 'Siegerehrung / Podest',
  winnersHelp: 'Präsentiert die Erstplatzierten einer ausgewählten Kategorie prominent und großflächig für die Siegerehrung.',
  selectWinnerCategory: 'Gewinner-Kategorie auswählen',
  announcement: 'Durchsage / Info Screen',
  announcementHelp: 'Blendet eine bildschirmfüllende Nachricht ein (z.B. Beginn Siegerehrung).',
  editAnnouncement: 'Durchsage bearbeiten',
  currentAnnouncement: 'Aktueller Durchsagentext',
  preview: 'Vorschau anzeigen',
  editText: 'Text bearbeiten ✍️',
  headline: 'Titel',
  message: 'Nachricht',
  cancel: 'Abbrechen',
  headlinePlaceholder: 'z.B. Wichtige Durchsage',
  messagePlaceholder: 'z.B. Siegerehrung startet in 15 Minuten.',
  saveAndShow: 'Speichern & auf TV anzeigen 📢',
  noAnnouncement: 'Keine Durchsage konfiguriert.',
} as const;

export const logsText = {
  loadError: (status: number) => `Fehler beim Laden der Audit-Protokolle (${status})`,
  loadFallback: 'Fehler beim Laden der Audit-Protokolle.',
  searchPlaceholder: 'Audit-Protokoll durchsuchen (Benutzer, Aktion, Details)...',
  foundCount: (count: number) => `${count} ${count === 1 ? 'Eintrag' : 'Einträge'} gefunden`,
  refresh: 'Aktualisieren',
  loading: 'Lade Protokolle...',
  empty: 'Keine Audit-Einträge gefunden',
  differentSearch: 'Versuche einen anderen Suchbegriff.',
  noChanges: 'Es wurden noch keine Änderungen im System protokolliert.',
  timestamp: 'Zeitstempel',
  user: 'Benutzer',
  action: 'Aktion',
  detailsPreview: 'Details Vorschau',
  details: 'Diff / Details 🔍',
  previousPage: '← Vorherige',
  nextPage: 'Nächste →',
  page: (page: number, total: number) => `Seite ${page} von ${total}`,
  inspector: 'Audit-Details Inspektor',
  userLabel: 'Benutzer:',
  timestampLabel: 'Zeitstempel:',
  diffTitle: 'Vorher vs. Nachher Snapshot (JSON Diff)',
  previous: '🔻 VORHER (Previous)',
  next: '🔺 NACHHER (New)',
  snapshot: 'Protokollierte Details (JSON Snapshot)',
  close: 'Schließen',
  systemTitle: 'System & Wartung',
  systemDescription: 'Statusinformationen zur Cloudflare D1 Competition Engine.',
  clearDatabase: 'Datenbank leeren...',
  apiStatus: 'API Status',
  online: 'ONLINE (200 OK)',
  storageEngine: 'Speicher-Engine',
  storageValue: 'Cloudflare D1 / SQLite',
  categories: 'Kategorien',
  configuredEvaluations: (count: number) => `${count} Wertungen konfiguriert`,
  reset: {
    keyword: 'LÖSCHEN',
    error: (status: number) => `Fehler beim Zurücksetzen (${status})`,
    success: 'Datenbank wurde erfolgreich zurückgesetzt.',
    fallback: 'Fehler beim Zurücksetzen der Datenbank.',
    title: 'Datenbank zurücksetzen',
    warning: 'Wählen Sie die Datenbereiche aus, die unwiderruflich gelöscht werden sollen.',
    confirmBefore: 'Bitte tippen Sie',
    confirmAfter: 'ein, um den Vorgang zu bestätigen:',
    cancel: 'Abbrechen',
    deleting: 'Lösche...',
    deletePermanently: 'Ausgewählte Daten löschen',
    scopesTitle: 'Zu löschende Datenbereiche:',
    scopeCategoryEntries: 'Zeiteinträge & Startlisten',
    scopeCategoryEntriesDesc: 'Löscht alle erfassten Angriffs-/Staffelzeiten und Startnummern.',
    scopeGroups: 'Gruppen',
    scopeGroupsDesc: 'Löscht alle Gruppen (setzt Zeiteinträge voraus).',
    scopeFireBrigades: 'Feuerwehren',
    scopeFireBrigadesDesc: 'Löscht alle Feuerwehren (setzt Gruppen voraus).',
    scopeEvaluationTypes: 'Wertungen',
    scopeEvaluationTypesDesc: 'Löscht alle Ergebnis-Wertungen (setzt Zeiteinträge voraus).',
    scopeCategoryTypes: 'Bewerbskategorien',
    scopeCategoryTypesDesc: 'Löscht alle Bewerbsdisziplinen (setzt Wertungen voraus).',
    atLeastOneScope: 'Bitte wählen Sie mindestens einen Bereich zum Löschen aus.',
  },
} as const;

export const uiText = {
  common: commonText,
  auth: authText,
  adminLayout: adminLayoutText,
  adminTabs: adminTabsText,
  admin: {
    results: resultsText,
    participants: participantsText,
    broadcast: broadcastText,
    setup: setupText,
    settings: settingsText,
    logs: logsText,
  },
  publicScoreboard: publicScoreboardText,
  tv: tvText,
} as const;
